name: Advanced Notion Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  notion_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync Notion to README
        uses: dvanoni/notion-to-github-action@v2.0.0
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          template_file: './README.md'
          output_file: './README.md'
          marker: 'notion'

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Weekly Log from Notion" || echo "No changes to commit"
          git push
